### ISSUE TITLE
Crashes after first SCTE-35 cue recognition

### ISSUE THREAD

**Issue by lastrixx** [m2amedia/scte35dump#1]
Hi and thanks a lot for such a useful utility! 
But I faced a problem running it on my Ubuntu 18.04.1 LTS.
I have a file with several SCTE-35 cues, but the program only recognizes one and then chrashes like this:

```
~/scte35dump/target/debug$ ./scte35dump file ~/Sft-1.ts 
new table for pid 2030, program 2030
unhandled pid 17
[PMT pid:2030 program:2030] new entry PID 2031
[PMT pid:2030 program:2030] new entry PID 2032
[PMT pid:2030 program:2030] new entry PID 2035
Found SCTE-35 data on PID 2035 (0x7f3)
unhandled pid 20
SpliceInfoHeader { protocol_version: 0, encrypted_packet: false, encryption_algorithm: None, pts_adjustment: 0, cw_index: 255, tier: 4095 } SpliceInsert {
    splice_event_id: 1073742652,
    reserved: 127,
    splice_detail: Insert {
        network_indicator: Out,
        splice_mode: Program(
            Timed(
                Some(
                    4262842406
                )
            )
        ),
        duration: Some(
            SpliceDuration {
                return_mode: Manual,
                duration: 14850000
            }
        ),
        unique_program_id: 1,
        avail_num: 21,
        avails_expected: 255
    }
}
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 3', /home/lastrixx/.cargo/registry/src/github.com-1ecc6299db9ec823/scte35-reader-0.3.0/src/lib.rs:230:51
note: Run with `RUST_BACKTRACE=1` for a backtrace.

```

I'd appreciate very much if you could help me with this and I can provide any addinional information you may need.

Here is the backtrace which it gives when env RUST_BACKTRACE=1 is ON:

```
new table for pid 2030, program 2030
unhandled pid 17
[PMT pid:2030 program:2030] new entry PID 2031
[PMT pid:2030 program:2030] new entry PID 2032
[PMT pid:2030 program:2030] new entry PID 2035
Found SCTE-35 data on PID 2035 (0x7f3)
unhandled pid 20
SpliceInfoHeader { protocol_version: 0, encrypted_packet: false, encryption_algorithm: None, pts_adjustment: 0, cw_index: 255, tier: 4095 } SpliceInsert {
    splice_event_id: 1073742652,
    reserved: 127,
    splice_detail: Insert {
        network_indicator: Out,
        splice_mode: Program(
            Timed(
                Some(
                    4262842406
                )
            )
        ),
        duration: Some(
            SpliceDuration {
                return_mode: Manual,
                duration: 14850000
            }
        ),
        unique_program_id: 1,
        avail_num: 21,
        avails_expected: 255
    }
}
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 3', /home/lastrixx/.cargo/registry/src/github.com-1ecc6299db9ec823/scte35-reader-0.3.0/src/lib.rs:230:51
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: rust_begin_unwind
             at libstd/panicking.rs:337
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   8: core::panicking::panic_bounds_check
             at libcore/panicking.rs:60
   9: scte35_reader::SpliceDescriptor::parse
             at /home/lastrixx/.cargo/registry/src/github.com-1ecc6299db9ec823/scte35-reader-0.3.0/src/lib.rs:230
  10: <scte35_reader::SpliceDescriptorIter<'buf> as core::iter::iterator::Iterator>::next
             at /home/lastrixx/.cargo/registry/src/github.com-1ecc6299db9ec823/scte35-reader-0.3.0/src/lib.rs:291
  11: <scte35dump::mpegts::DumpSpliceInfoProcessor as scte35_reader::SpliceInfoProcessor>::process
             at src/mpegts.rs:12
  12: <scte35_reader::Scte35SectionProcessor<P, Ctx> as mpeg2ts_reader::psi::SectionProcessor>::start_section
             at /home/lastrixx/.cargo/registry/src/github.com-1ecc6299db9ec823/scte35-reader-0.3.0/src/lib.rs:332
  13: <mpeg2ts_reader::psi::SectionPacketConsumer<P>>::consume
             at /home/lastrixx/.cargo/registry/src/github.com-1ecc6299db9ec823/mpeg2ts-reader-0.4.0/src/psi.rs:443
  14: <scte35dump::mpegts::Scte35StreamConsumer as mpeg2ts_reader::demultiplex::PacketFilter>::consume
             at src/mpegts.rs:60
  15: <mpeg2ts_reader::demultiplex::Demultiplex<Ctx>>::push
             at /home/lastrixx/scte35dump/<packet_filter_switch macros>:8
             at /home/lastrixx/.cargo/registry/src/github.com-1ecc6299db9ec823/mpeg2ts-reader-0.4.0/src/demultiplex.rs:690
  16: scte35dump::file_main
             at src/main.rs:72
  17: scte35dump::main
             at src/main.rs:102
  18: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  19: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  20: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  21: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  22: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  23: main
  24: __libc_start_main
  25: _start

```

**Comment by dholroyd** [comment]
Many thanks for the report!

Could you provide a minimal fragment of TS which demonstrates the problem?

**Comment by dholroyd** [comment]
FWIW, initial attempt at a fix in https://github.com/dholroyd/scte35-reader/commit/c6be75ceda7c9f6ef214a8679973d1101808fcfb

**Comment by lastrixx** [comment]
Hi! I will try to upload the stream fragments somewhere.
Meanwhile, I'm completely new to Rust. Woul you plese explain how should I update that particular sct35-reader library on my machine? 'cargo fetch' doesn't help

**Comment by lastrixx** [comment]
https://privnote.com/iMEs7QVB#sUoTX5BwP

here are the TS files with some notes
(made a self-destructing message in order to avoid any copyright issues)

**Comment by dholroyd** [comment]
A pair of 4GB files is not quite the kind of 'minimal' I had in mind - my poor internet connection is :boom:  :grinning:

Don't worry about updating sct35-reader if you're unfamiliar, I'll push out new releases once I've had the chance to download and test with the examples you've provided, then hopefully you can just `cargo install` the new version of scte35dump.

**Comment by dholroyd** [comment]
So I think the problem was that I didn't have any examples where the scte data included descriptors, and the descriptor handling was just broken.

The change above seems to address that for as much of the first example as has downloaded so far,

```
new table for pid 2030, program 2030                                                                                                                                                                     [470/9790]
unhandled pid 17                                                                                                                                                                                                   
[PMT pid:2030 program:2030] new entry PID 2031                                                                                                                                                                     
[PMT pid:2030 program:2030] new entry PID 2032                                                                                                                                                                     
[PMT pid:2030 program:2030] new entry PID 2035                                                                                                                                                                     
Found SCTE-35 data on PID 2035 (0x7f3)                                                                                                                                                                             
unhandled pid 20                                                                                                                                                                                                   
SpliceInfoHeader { protocol_version: 0, encrypted_packet: false, encryption_algorithm: None, pts_adjustment: 0, cw_index: 255, tier: 4095 } SpliceInsert {                                                         
    splice_event_id: 1073742652,                                                                                                                                                                                   
    reserved: 127,                                                                                                                                                                                                 
    splice_detail: Insert {                                                                                                                                                                                        
        network_indicator: Out,                                                                                                                                                                                    
        splice_mode: Program(                                                                                                                                                                                      
            Timed(                                                                                                                                                                                                 
                Some(                                                                                                                                                                                              
                    4262842406                                                                                                                                                                                     
                )                                                                                                                                                                                                  
            )                                                                                                                                                                                                      
        ),                                                                                                                                                                                                         
        duration: Some(                                                                                                                                                                                            
            SpliceDuration {                                                                                                                                                                                       
                return_mode: Manual,                                                                                                                                                                               
                duration: 14850000                                                                                                                                                                                 
            }                                                                                                                                                                                                      
        ),                                                                                                                                                                                                         
        unique_program_id: 1,                                                                                                                                                                                      
        avail_num: 21,                                                                                                                                                                                             
        avails_expected: 255                                                                                                                                                                                       
    }                                                                                                                                                                                                              
}                                                                                                                                                                                                                  
  Ok(AvailDescriptor { provider_avail_id: 21 })                                                                                                                                                                    
SpliceInfoHeader { protocol_version: 0, encrypted_packet: false, encryption_algorithm: None, pts_adjustment: 0, cw_index: 255, tier: 4095 } SpliceInsert {                                                         
    splice_event_id: 1073742652,                                                                                                                                                                                   
    reserved: 127,                                                                                                                                                                                                 
    splice_detail: Insert {                                                                                                                                                                                        
        network_indicator: Out,                                                                                                                                                                                    
        splice_mode: Program(                                                                                                                                                                                      
            Timed(                                                                                                                                                                                                 
                Some(                                                                                                                                                                                              
                    4262842406
                )
            )
        ),
        duration: Some(
            SpliceDuration {
                return_mode: Manual,
                duration: 14850000
            }
        ),
        unique_program_id: 1,
        avail_num: 21,
        avails_expected: 255
    }
}
  Ok(AvailDescriptor { provider_avail_id: 21 })
...
```

Will have a look at the second example some time tomorrow.

**Comment by dholroyd** [comment]
Hi!

Please try to `cargo install scte35dump` to get the latest version (you might need to `cargo uninstall scte35dump` if you already have the previous release installed).

Let me know how you get on.

**Comment by lastrixx** [comment]
Works! This means that I don't need to endlessly scroll&click the DVB Inspector tree any more - that's pure happines, thank you so much!!!

**Comment by dholroyd** [comment]
Glad to hear it works :+1: 

By the way, I am curious to understand how others use scte35dump in their workflows.  If you feel like sharing a few words about the problems it solves for you, that's would be awesome!

**Comment by lastrixx** [comment]
I'm doing some analytics about commercial breaks, their durations and position in the program.

**Comment by ashoktk11** [comment]
Hi, Observing similar crash issue,

SpliceInfoHeader { protocol_version: 0, encrypted_packet: false, encryption_algorithm: None, pts_adjustment: 6913847087, cw_index: 0, tier: 4095 } TimeSignal {
    splice_time: Timed(
        Some(
            1683572058,
        ),
    ),
}
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `144`,
 right: `152`', /home/vagrant/.cargo/registry/src/github.com-1ecc6299db9ec823/scte35-reader-0.6.0/src/lib.rs:536:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

Link for sample file for analysis > http://www.mediafire.com/file/35mlgowmq10x16a/time_signal.ts/file

**Comment by dholroyd** [comment]
@ashoktk11; opened #4, since your report is a distinct problem from the one originally reported on this ticket.
